#%RAML 1.0 Library

types:
  Picture:
    type: object
    required: false
    description: The user's profile picture.
    properties:
      url:
        type: string
        required: false
        description: A URL that points to a profile picture of this user.
  Resource:
    displayName: Resource
    description: A reference to a file's parent.
    type: object
    properties: 
      kind:
        type: string
        required: false
        description: This is always drive#parentReference.
        enum: [drive#parentReference]
        default: drive#parentReference
      id:
        type: string
        description: The ID of the parent
      selfLink:
        type: string
        description: A link back to this reference
      parentLink:
        type: string
        description: A link to the parent
      isRoot:
        type: string
        description: Whether or not the parent is the root folder.
  Owners:
    displayName: Owners
    description: The owner(s) of a file.
    type: object
    properties:
      kind:
        type: string
        required: false
        description: This is always drive#user.
        default: drive#user
        enum: [drive#user]
      displayName:
        type: string
        required: false
        description: A plain text displayable name for this user.
        example: Owner display name
      picture:
        type: Picture
        required: false
      isAuthenticatedUser:
        type: boolean
        required: false
        description: Whether this user is the same as the authenticated user for whom the request was made.
      permissionId:
        type: string
        required: false
        description: The user's ID as visible in the permissions collection.
      emailAddress:
        type: string
        required: false
        description: The email address of the user.