#%RAML 1.0 Library

uses: 
  BaseTypes: !include base-types.raml
  PermissionsLib: !include permission-lib.raml

types:
  DriveFile:
    displayName: File
    properties: 
      kind:
        type: string
        description: The type of file. This is always drive#file.
        default: drive#file
      id:
        type: string
        description: The ID of the file.
      etag:
        type: string
        description: ETag of the file.
      selfLink:
        type: string
        description: A link back to this file.
      webContentLink:
        type: string
        description: | 
          A link for downloading the content of the file in a browser using cookie based authentication. 
          In cases where the content is shared publicly, the content can be downloaded without any credentials.
      webViewLink:
        type: string
        description: | 
          A link only available on public folders for viewing their static web assets (HTML, CSS, JS, etc) 
          via Google Drive's Website Hosting.
      alternateLink:
        type: string
        description: A link for opening the file in a relevant Google editor or viewer.
      embedLink:
        type: string
        description: A link for embedding the file.
      openWithLinks:
        type: object
        description: | 
          A map of the id of each of the user's apps to a link to open this file with that app. 
          Only populated when the drive.apps.readonly scope is used.
      defaultOpenWithLink:
        type: string
        description: A link to open this file with the user's default app for this file. Only populated when the drive.apps.readonly scope is used.
      iconLink:
        type: string
        description: A link to the file's icon
      thumbnailLink:
        type: string
        description: A short-lived link to the file's thumbnail. Typically lasts on the order of hours.
      thumbnail:
        type: !include thumbnail.raml
      title:
        type: string
        description: The title of the file. Used to identify file or folder name.
      mimeType:
        type: string
        description: |
          The MIME type of the file. This is only mutable on update when uploading new content. 
          This field can be left blank, and the mimetype will be determined from the uploaded content's MIME type.
      description:
        type: string
        description: A short description of the file.
      labels:
        type: !include file-labels.raml
      createdDate:
        type: datetime
        description: Create time for this file (formatted RFC 3339 timestamp)
      modifiedDate:
        type: datetime
        description: Last time this file was modified by anyone (formatted RFC 3339 timestamp). This is only mutable on update when the setModifiedDate parameter is set.
      modifiedByMeDate:
        type: datetime
        description: Last time this file was modified by the user (formatted RFC 3339 timestamp). Note that setting modifiedDate will also update the modifiedByMe date for the user which set the date.
      lastViewedByMeDate:
        type: datetime
        description: Last time this file was viewed by the user (formatted RFC 3339 timestamp).
      markedViewedByMeDate:
        type: datetime
        description: Deprecated
      sharedWithMeDate:
        type: datetime
        description: Time at which this file was shared with the user (formatted RFC 3339 timestamp).
      version:
        type: integer
        description: A monotonically increasing version number for the file. This reflects every change made to the file on the server, even those not visible to the requesting user.
      sharingUser:
        type: !include sharing-user.raml
      parents:
        type: array
        items: [BaseTypes.Resource]
      downloadUrl:
        type: string
        description: An URL to download the content of the file.
      exportLinks:
        type: object
        description: |
          Links for exporting Google Docs to specific formats.
          The key in the object is a mapping from export format to URL
      indexableText:
        type: object
        description: Indexable text attributes for the file. This property can only be written, and is not returned by files.get. For more information, see Custom thumbnails and indexable text.
        properties:
          text:
            type: string
            description: The text to be indexed for this file.
      userPermission:
        type: string
        description: 
      permissions:
        type: array
        description: The permissions for the authenticated user on this file.
        items: [PermissionsLib.Permissions]
      originalFilename: 
        type: string
        description: The original filename of the uploaded content if available, or else the original value of the title field. `This is only available for files with binary content in Drive.`
      fileExtension:
        type: string
        description: The final component of fullFileExtension with trailing text that does not appear to be part of the extension removed. This field is only populated for files with content stored in Drive; it is not populated for Google Docs or shortcut files.
      md5Checksum:
        type: string
        description: An MD5 checksum for the content of this file. This field is only populated for files with content stored in Drive; it is not populated for Google Docs or shortcut files.
      fileSize:
        type: integer
        description: The size of the file in bytes. This field is only populated for files with content stored in Drive; it is not populated for Google Docs or shortcut files.
      quotaBytesUsed:
        type: integer
        description: The number of quota bytes used by this file.
      ownerNames:
        type: array
        items: [string]
        description: Name(s) of the owner(s) of this file.
      owners:
        type: array
        items: [BaseTypes.Owners]
        description: The owner(s) of this file.
      lastModifyingUserName:
        type: string
        description: Name of the last user to modify this file
      lastModifyingUser:
        type: object
        description: The last user to modify this file
        properties:
          kind:
            type: string
            description: This is always drive#user.
            default: drive#user
            enum: [drive#user]
          displayName:
            type: string
            description: A plain text displayable name for this user.
          picture:
            type: BaseTypes.Picture
          isAuthenticatedUser:
            type: boolean
            description: Whether this user is the same as the authenticated user for whom the request was made.
          permissionId:
            type: string
            description: The user's ID as visible in the permissions collection.
          emailAddress:
            type: string
            description: The email address of the user. This field is returned only if the last modifying user is an owner of the file, the requesting user is an owner or can modify the file, or if the last modifying user's email address is visible.
      editable:
        type: boolean
        description: Whether the file can be edited by the current user.
      copyable:
        type: boolean
        description: Whether the file can be copied by the current user.
      writersCanShare:
        type: boolean
        description: Whether writers can share the document with other users
      shared:
        type: boolean
        description: Whether the file has been shared
      explicitlyTrashed:
        type: boolean
        description: Whether this file has been explicitly trashed, as opposed to recursively trashed.
      appDataContents:
        type: boolean
        description: Whether this file is in the Application Data folder.
      headRevisionId:
        type: string
        description: The ID of the file's head revision. This field is only populated for files with content stored in Drive; it is not populated for Google Docs or shortcut files.
      folderColorRgb:
        type: string
        description: Folder color as an RGB hex string if the file is a folder. The list of supported colors is available in the folderColorPalette field of the About resource. If an unsupported color is specified, it will be changed to the closest color in the palette.
      imageMediaMetadata:
        type: object
        description: Metadata about image media. This will only be present for image types, and its contents will depend on what can be parsed from the image content.
        properties:
          width:
            type: integer
            description: The width of the image in pixels.
            minimum: 0
          height:
            type: integer
            description: The height of the image in pixels.
            minimum: 0
          rotation:
            type: integer
            description: The rotation in clockwise degrees from the image's original orientation.
          location:
            type: object
            description: Geographic location information stored in the image.
            properties:
              latitude:
                type: number
                description: The latitude stored in the image.
              longitude:
                type: number
                description: The longitude stored in the image.
              altitude:
                type: number
                description: The altitude stored in the image.
          date:
            type: datetime
            description: The date and time the photo was taken (EXIF format timestamp).
          cameraMake:
            type: string
            description: The make of the camera used to create the photo.
          cameraModel:
            type: string
            description: The model of the camera used to create the photo.
          exposureTime:
            type: number
            description: The length of the exposure, in seconds.
            minimum: 0
          aperture:
            type: number
            description: The aperture used to create the photo (f-number).
            minimum: 0
          flashUsed:
            type: boolean
            description: Whether a flash was used to create the photo.
          focalLength:
            type: number
            description: The focal length used to create the photo, in millimeters.
            minimum: 0
          isoSpeed:
            type: integer
            description: The ISO speed used to create the photo.
            minimum: 0
          meteringMode:
            type: string
            description: The metering mode used to create the photo.
          sensor:
            type: string
            description: The type of sensor used to create the photo.
          exposureMode:
            type: string
            description: The exposure mode used to create the photo.
          colorSpace:
            type: string
            description: The color space of the photo.
          whiteBalance:
            type: string
            description: The white balance mode used to create the photo.
          exposureBias:
            type: number
            description: The exposure bias of the photo (APEX value). 
          maxApertureValue:
            type: number
            description: The smallest f-number of the lens at the focal length used to create the photo (APEX value). 
          subjectDistance:
            type: integer
            description: The distance to the subject of the photo, in meters.
            minimum: 0
          lens:
            type: string
            description: The lens used to create the photo.
      videoMediaMetadata:
        type: object
        description: Metadata about video media. This will only be present for video types.
        properties:
          width:
            type: integer
            description: The width of the video in pixels.
            minimum: 0
          height:
            type: integer
            description: The height of the video in pixels.
            minimum: 0
          durationMillis:
            type: number
            description: The duration of the video in milliseconds.
            minimum: 0
  DriveFileCreate:
    displayName: File
    description: A type to be used when a new file to be created. 
    properties: 
      id:
        type: string
        description: The ID of the file.
      title:
        type: string
        description: The title of the file. Used to identify file or folder name.
      mimeType:
        type: string
        description: |
          The MIME type of the file. This is only mutable on update when uploading new content. 
          This field can be left blank, and the mimetype will be determined from the uploaded content's MIME type.
      description:
        type: string
        description: A short description of the file.
      labels:
        type: !include file-labels.raml
      modifiedDate:
        type: datetime
        description: Last time this file was modified by anyone (formatted RFC 3339 timestamp). This is only mutable on update when the setModifiedDate parameter is set.
      lastViewedByMeDate:
        type: datetime
        description: Last time this file was viewed by the user (formatted RFC 3339 timestamp).
      markedViewedByMeDate:
        type: datetime
        description: Deprecated
      parents:
        type: array
        items: [BaseTypes.Resource]
      indexableText:
        type: object
        description: Indexable text attributes for the file. This property can only be written, and is not returned by files.get. For more information, see Custom thumbnails and indexable text.
        properties:
          text:
            type: string
            description: The text to be indexed for this file.
      originalFilename: 
        type: string
        description: The original filename of the uploaded content if available, or else the original value of the title field. `This is only available for files with binary content in Drive.`
      writersCanShare:
        type: boolean
        description: Whether writers can share the document with other users.